### ISSUE TITLE
Using Weasel-Diesel for documentation only

### ISSUE THREAD

**Issue by onsails** [mattetti/Weasel-Diesel#15]
Hello,

We love how it generates docs but we prefer to implement APIs on the other software stack than ruby / rails.
Is there a way of using Weasel-Diesel for api documentation but not for implementation? If I don't describe `service.implementation` block a command `rake doc:services` exits with an error `DSL is missing the implementation block`.

**Comment by mattetti** [comment]
That's a good point, the rake generation task only exists in `wd_sinatra` and that's why you are saying the error about missing implementation block. The task could probably be ported over to WD itself and require a source path for the API descriptions and an output path for the documentation.
I don't quite have time for that at the moment, but patches are welcome if you want that done ASAP.

**Comment by kamui** [comment]
#30 closes this. To generate docs:

``` bash
$ weasel_diesel generate_doc <path to ruby source files>
```
