### ISSUE TITLE
Top Level Array Response Function

### ISSUE THREAD

**Issue by dsshap** [mattetti/Weasel-Diesel#26]
Hi, 

Any way we can get a release of the this gem with the top level array response functionality?

Or is there a hot fix I can implement in v1.2.1 that could get me this?

**Comment by dsshap** [comment]
I am also using a forked version of wd-sinatra, needed to set a version on minitest

**Comment by mattetti** [comment]
I'm confused, do you want me to release master as a new gem? I thought I didn't release the top level array response error yet.

**Comment by dsshap** [comment]
Hey, thanks for taking the time.

I was interested in seeing if you could release a new version of this gem, to include the top level array response ability. I am avoiding the error being thrown in my tests by not calling assert_api_response. 

If you don't want to release it, what time line could one expect for a new release that includes the top level arrays supported in the json validation?

**Comment by mattetti** [comment]
If master doesn't currently work for you, I'm afraid I won't be able to add
top level array response right away since I'm in the process of launching
my startup :(
If you just want me to cut a gem, I'd be glad to do so. Otherwise I'm
afraid without a PR I won't be able to get that feature in any time soon.

**Comment by kamui** [comment]
Maybe he's referring to #25? It looks like @raul added a PR for top level array response support.
